#!/bin/bash
echo $PATH |tr ":" "\n" | wC -l
echo '#!/bin/bash' > count_path_dirs.sh && echo 'IFS=":"' >> count_path_dirs.sh && echo 'dirs=($PATH)' >> count_path_dirs.sh && echo 'count=${#dirs[@]}' >> count_path_dirs.sh && echo 'echo "Number of directories in PATH: $count"' >> count_path_dirs.sh

